### ISSUE TITLE
Suggest to use airbnb code style 

### ISSUE THREAD

**Issue by Celthi** [takashiro/asmodee-werewolf-server#4]
I prefer the style of https://github.com/airbnb/javascript  :) :

**Comment by takashiro** [comment]
Updated to `airbnb-base` in c453e2ddb31e337d79de0947bb1cc5fd435928a3.
Changed some rules though 🤣

**Comment by Celthi** [comment]
Great. I'll start to learn the code again in a near future (my wish).
